# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_type_identifier', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('authentication_token', models.CharField(max_length=255)),
                ('data', models.FileField(upload_to='passes')),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_library_identifier', models.CharField(max_length=64)),
                ('push_token', models.CharField(max_length=64)),
                ('pazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_passbook.Pass')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pass',
            unique_together=set([('pass_type_identifier', 'serial_number')]),
        ),
    ]
