# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_passbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pass',
            options={'verbose_name': 'passes'},
        ),
        migrations.AlterField(
            model_name='registration',
            name='push_token',
            field=models.CharField(max_length=255),
        ),
    ]
