# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-24 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_passbook', '0002_push_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='push_token',
            field=models.TextField(),
        ),
    ]
